# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1
  - nightly
env:
  matrix:
    - JULIA_NUM_THREADS=1
    - JULIA_NUM_THREADS=2

codecov: true
coeveralls: true

git:
  depth: 999999
notifications:
  email: false

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

cache:
  directories:
  - $HOME/.julia/artifacts
  - $HOME/.julia/conda

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Test against Astropy"
      julia: 1.4
      os: linux
      script:
        - julia --color=yes -e 'using Pkg; Pkg.add("PyCall"); Pkg.add("Conda"); using LombScargle, Conda; Conda.add("astropy"); include(joinpath(dirname(pathof(LombScargle)), "..", "test", "astropy.jl"))'
      after_success: skip
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
